name: 'Run All Unit & Security Tests'
description: 'Installs dependencies and runs npm test and npm audit for all Cloud Functions'

runs:
  using: "composite"
  steps:
    - name: Run Unit & Security Tests for All Modules
      shell: bash
      run: |
        FUNCTIONS_TO_TEST=("trigger_ingestion_cycle" "fetch_source_data" "filter_article_content" "core_analysis" "external_verification" "internal_qc" "decision_engine" "delivery_alerter" "get_manual_review" "submit_correction")
        for FUNCTION in "${FUNCTIONS_TO_TEST[@]}"
        do
          echo "--- Testing module: $FUNCTION ---"
          cd $FUNCTION
          npm install
          npm test
          npm audit
          cd ..
          echo "--- Finished $FUNCTION ---"
          echo ""
        done
