name: PR Validation Checks

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Validate Terraform
        id: validate_tf
        run: |
          cd pipeline
          terraform init
          terraform validate

      - name: Terraform Plan
        id: plan_tf
        env:
          TF_VAR_GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_EMAIL_FROM: ${{ secrets.TF_VAR_EMAIL_FROM }}
          TF_VAR_EMAIL_TO: ${{ secrets.TF_VAR_EMAIL_TO }}
        run: |
          cd pipeline
          terraform plan -no-color

      - name: Run Unit & Security Tests for All Modules
        id: run_tests
        run: |
          FUNCTIONS=("trigger_ingestion_cycle" "fetch_source_data" "filter_article_content" "core_analysis" "external_verification" "internal_qc" "decision_engine" "delivery_alerter" "get_manual_review" "submit_correction")
          for FUNCTION in "${FUNCTIONS[@]}"
          do
            echo "--- Validating module: $FUNCTION ---"
            cd $FUNCTION
            npm install
            npm test
            npm audit
            cd ..
            echo "--- Finished $FUNCTION ---"
            echo ""
          done
